compute Twater water temp
compute Tgraph graph temp

thermo          1000
thermo_style custom step etotal evdwl ecoul elong ebond eangle ke pe temp c_Twater c_Tgraph &
 press vol density cpu
thermo_modify flush yes

dump 1 all custom 5000 ${run}.dump id type element x y z xu yu zu vx vy vz mol
dump_modify 1 element O H C C O H

timestep 1   # 1fs


compute water_chunk water chunk/atom bin/1d z center 1 units box
compute 6 water temp/chunk water_chunk temp com yes 


# —————————————————————————————
# Equilibration (50ps)  
# —————————————————————————————
fix mom graph momentum 100 linear 1 1 1

fix		t1 all nve
fix             t3 water langevin ${temp}  ${temp}  100. 231634
fix_modify      t3 temp Twater
fix             t4 graph langevin ${temp2} ${temp2} 100. 643241
fix_modify      t4 temp Tgraph

compute 3 graph pe/atom
compute 5 graph reduce sum c_3
compute 4 graph ke

fix temp_w water ave/time 1 1 10 c_Twater file system_h2o.txt
fix temp_graph graph ave/time 1 1 10 c_Tgraph file system_graph.txt 
fix PotEn graph ave/time 1 1 10 c_5 file potential_graph.txt 
fix KinEn graph ave/time 1 1 10 c_4 file kinetic_graph.txt 
fix temp_chunk_bias water ave/time 1 1 10 c_6[1] file temp_chunk_bias_1A.out mode vector
fix temp_chunk water ave/chunk 1 1 50000 water_chunk temp ave one file slab_position_check.txt

run 50000


unfix t1
unfix t3
unfix t4


# —————————————————————————————  
# Production run (1000ps)  
# —————————————————————————————  
fix 1 all nve

thermo_style custom elapsed etotal evdwl ecoul elong ebond eangle ke pe temp &
 press vol density c_Twater c_Tgraph c_5 c_4 cpu

run 1000000

